baseurl = "/"
languageCode = "es-ES"
title = "OSOCO"
theme = "hugo-osoco-theme"
disqusShortname = "osoco"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	name = "OSOCO website"
	description = "Describe your website"

	# Format dates with Go's time formatting
	date_format = "02-01-2006"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

	[params.social]
		# The icons will be shown if you enter your username
  	twitter = "osoco"
		github = "osoco"
		linkedin = "osoco"
		slideshare = "osoco"
		vimeo = "osoco"

	[params.copyright]
		notice = "OSOCO &copy; 2017"

  [params.banner]
    [params.banner.home]
      claim = "Tenemos la convicción de que otra forma de trabajar es posible"

  [params.intro]
    hide  = false
    title = "Somos OSOCO"
    highlighted = "Cuidamos mucho los intangibles,<br> como el ambiente de trabajo <br> o la cultura de empresa, <br> que hacen que el resultado <br> sea el que perseguimos: <br> mejor de lo esperado."
    quote = "Nuestro objetivo siempre es <br> superar las expectativas de nuestros clientes,<br> presentándoles un resultado <br> mejor de lo esperado."
    contents = [
      "Somos una compañía de diseño y desarrollo de software fundada en 2003, con base en Madrid, España.",
      "Tenemos experiencia creando software, tanto para pequeñas y medianas empresas, como aplicaciones de misión crítica para grandes empresas,</strong> especialmente usando la plataforma Java EE y otras tecnologías como Groovy y Grails.",
      "El equipo de **OSOCO** está formado por ingenieros altamente cualificados (informáticos y de telecomunicación), que se sienten orgullosos de serlo, pero que también entienden el desarrollo de software como una artesanía. Si tenemos en cuenta la definición de la RAE, lo que diferencia a un artesano es que imprime su sello personal en su trabajo. En **OSOCO** cuidamos con esmero cada detalle de nuestros proyectos, desde sus fases iniciales hasta el despliegue en producción.",
      """Nuestra visión consistió en crear una empresa pequeña, pero cumplidora, seria y responsable; es decir, **una empresa de verdaderos profesionales de la programación**, con una propuesta basada en la consistencia y calidad de nuestros trabajos, fundamentada en los siguientes valores:

* Profesionalidad
* Agilidad
* Pasión por la tecnología
* Cuidado del detalle"""
    ]





	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Strata**, a super simple<br> responsive site template freebie<br> crafted by [HTML5 UP](//html5up.net)."
		# The icons will be shown if you enter your username
		twitter = "osoco"
		github = "osoco"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "osoco"

		copyright = [
			"&copy; John Doe",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]




	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
			#
			# What you need to do for the setup?
			#
			# - set your email address under 'email' below
			# - upload the generated site to your server
			# - send a dummy email yourself to confirm your account
			# - click the confirm link in the email from www.formspree.io
			# - you're done. Happy mailing!
		email = "hola@osoco.es"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "NOSOTROS"
	url  = "/nosotros"
	weight = 0

[[menu.main]]
	name = "PROYECTOS"
	url  = "/proyectos"
	weight = 5

[[menu.main]]
	name = "CONTACTO"
	url  = "/contacto"
	weight = 10
